apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-node-exporter
  targetNamespace: node-exporter
  createNamespace: true
  version: 4.47.1
  valuesContent: |-
    {}