apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wordpress
  namespace: wordpress
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: wordpress
  targetNamespace: wordpress
  valuesContent: |-
    wordpressUsername: admin
    wordpressPassword: "MySecurePassword"
    wordpressEmail: admin@example.com
    wordpressBlogName: "My WordPress Site"
    
    service:
      type: ClusterIP
    
    persistence:
      enabled: true
      size: 5Gi
    
    mariadb:
      enabled: true
      auth:
        rootPassword: "MySQLRootPassword"
        password: "MySQLPassword"
      primary:
        persistence:
          enabled: true
          size: 5Gi
        
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
