apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kafka
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: kafka
  targetNamespace: kafka
  valuesContent: |-
    kraft:
      enabled: true # Use KRaft instead of Zookeeper

    # Minimal single-node setup
    controller:
      automountServiceAccountToken: true
      replicaCount: 1
      heapOpts: -Xmx1024m -Xms1024m
      resources:
        limits:
          cpu: 1
          memory: 2Gi

    listeners:
      advertisedListeners: 'CLIENT://debian-k3s:9092,INTERNAL://debian-k3s:9094,EXTERNAL://debian-k3s:9095'

    extraConfigYaml:
      auto.create.topics.enable: true
      default.replication.factor: 1
      offsets.topic.replication.factor: 1

    externalAccess:
      enabled: true
      autoDiscovery:
        enabled: true

    rbac:
      create: true
    
    # Disable persistence for local testing
    persistence:
      enabled: false
    
    # Minimal resource usage
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 512Mi