apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: minio
  namespace: kube-system
spec:
  repo: https://charts.min.io/
  chart: minio
  targetNamespace: minio
  valuesContent: |-
    rootUser: rootuser
    rootPassword: rootpass123
    mode: standalone
    replicas: 1
    persistence:
      size: 10Gi
    buckets:
      - name: default-bucket
        policy: upload
        purge: false
        versioning: false
        objectlocking: false
    users:
      - accessKey: console
        secretKey: console123
        policy: consoleAdmin
      - accessKey: miniouser1
        secretKey: minio123
        policy: readwrite
    resources:
      requests:
        memory: 512Mi
