apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: demoapp
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/brandonros/hull-wrapper/master/
  chart: hull-wrapper
  targetNamespace: demoapp
  createNamespace: true
  version: 0.2.0
  valuesContent: |-
    hull:
      config:
        general:
          nameOverride: demoapp
          rbac: false
          noObjectNamePrefixes: true
      objects:
        serviceaccount:
          default:
            enabled: false
        deployment:
          demoapp:
            replicas: 2
            pod:
              containers:
                demoapp:
                  resources:
                    requests:
                      memory: 256Mi
                      cpu: 250m
                    limits:
                      memory: 2048Mi
                      cpu: 2000m
                  image:
                    repository: ghcr.io/brandonros/java-demoapp
                    tag: 3b435dbfebca682bfef4b3a196555e21cbfa6724
                  env:
                    SERVER_PORT:
                      value: 8080
                    SPRING_DATASOURCE_PRIMARY_URL:
                      value: "jdbc:sqlserver://mssql.mssql.svc.cluster.local:1433;databaseName=db;encrypt=true;trustServerCertificate=true"
                    SPRING_DATASOURCE_PRIMARY_USERNAME:
                      value: sa
                    SPRING_DATASOURCE_PRIMARY_PASSWORD:
                      value: Test_Password123!
                    MANAGEMENT_OTLP_TRACING_ENDPOINT:
                      value: http://jaeger.jaeger.svc.cluster.local:4318/v1/traces
                  ports:
                    http:
                      containerPort: 8080
        service:
          demoapp:
            type: ClusterIP
            ports:
              http:
                port: 8080
                targetPort: 8080
