apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rabbitmq
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: rabbitmq
  targetNamespace: rabbitmq
  valuesContent: |-
    clustering:
      enabled: false

    ldap:
      enabled: false

    persistence:
      enabled: false

    auth:
      username: user
      password: rabbitmq123
      securePassword: false
      enableLoopbackUser: false

    replicaCount: 1
