apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: graphite
  namespace: kube-system
spec:
  repo: https://kiwigrid.github.io
  chart: graphite
  targetNamespace: monitoring
  valuesContent: |-
    image:
      repository: graphiteapp/graphite-statsd
      tag: 1.1.10-5
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 8080

    persistence:
      enabled: true
      size: 10Gi

    ingress:
      enabled: false

    timeZone: UTC

    statsd:
      interface: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: graphite-statsd
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: statsd
      port: 8125
      targetPort: 8125
      nodePort: 30000
      protocol: TCP
  selector:
    app.kubernetes.io/name: graphite
    app.kubernetes.io/instance: graphite
