apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: postgresql
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: postgresql
  targetNamespace: postgresql
  valuesContent: |-
    global:
      security:
        allowInsecureImages: true

    auth:
      postgresPassword: postgres123

    image:
      registry: ghcr.io
      repository: brandonros/pgsql-http-docker
      tag: ee2078ad4365d1122a610d7d0526c12ce45edd30

    primary:
      extendedConfiguration: |
        shared_preload_libraries = 'http'
        robinhood.bearer_token = '${ROBINHOOD_BEARER_TOKEN}'
        robinhood.account_number = '${ROBINHOOD_ACCOUNT_NUMBER}'

      initdb:
        scripts:
          create-extensions.sql: |
            CREATE EXTENSION http;
