apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${app_name}-letsencrypt-prod-issuer
  namespace: traefik
spec:
  acme:
    email: test@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: ${app_name}-letsencrypt-prod-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: ${app_name}-http-gateway
              namespace: traefik
              kind: Gateway