apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: elasticsearch
  targetNamespace: elasticsearch
  valuesContent: |-
    global:
      kibanaEnabled: true
    master:
      masterOnly: false
      replicaCount: 1
      heapSize: 1024m
      resources:
        limits:
          cpu: 4
          memory: 4Gi
    data:
      replicaCount: 0
    coordinating:
      replicaCount: 0
    ingest:
      replicaCount: 0
    kibana:
      configuration:
        server:
          publicBaseUrl: https://kibana.debian-k3s
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 512Mi
