apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  targetNamespace: traefik
  version: 33.0.0
  valuesContent: |-
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 8000
        protocol: TCP
      
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 8443
        protocol: TCP
        tls:
          enabled: true
          
      kafka:
        port: 9092
        expose:
          default: true
        exposedPort: 9092
        protocol: TCP

    gateway:
      enabled: false

    deployment:
      podAnnotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-log-level: debug

    logs:
      general:
        level: TRACE
      access:
        enabled: true

    providers:
      kubernetesIngress:
        enabled: false

      kubernetesGateway:
        enabled: true
        experimentalChannel: true