apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: debian-k3s-gateway-tls
  namespace: traefik
spec:
  secretName: debian-k3s-gateway-tls

  issuerRef:
    name: debian-k3s-ca-issuer
    kind: ClusterIssuer

  dnsNames:
    # monitoring
    - grafana.debian-k3s
    - tempo.debian-k3s
    - prometheus.debian-k3s
    - graphite.debian-k3s

    # linkerd-viz
    - linkerd-viz.debian-k3s
