apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gateway
  namespace: traefik
  annotations:
    cert-manager.io/issuer: letsencrypt-prod-issuer
spec:
  gatewayClassName: traefik
  listeners:
    # wordpresstest5555
    - name: wordpress-http
      hostname: wordpresstest5555.duckdns.org
      port: 8000 # must match exposed port in traefik chart
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: wordpress-https
      hostname: wordpresstest5555.duckdns.org
      port: 8443 # must match exposed port in traefik chart
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: wordpresstest5555-prod-tls

    # pdf-generator5555
    - name: pdf-generator-http
      hostname: pdf-generator5555.duckdns.org
      port: 8000 # must match exposed port in traefik chart
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: pdf-generator-https
      hostname: pdf-generator5555.duckdns.org
      port: 8443 # must match exposed port in traefik chart
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: pdf-generator5555-prod-tls