apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: dispatcher
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/brandonros/hull-wrapper/master/
  chart: hull-wrapper
  targetNamespace: dispatcher
  createNamespace: true
  version: 0.2.0
  valuesContent: |-
    hull:
      config:
        general:
          nameOverride: dispatcher
          rbac: false
          noObjectNamePrefixes: true
      objects:
        serviceaccount:
          default:
            enabled: false
        deployment:
          dispatcher:
            replicas: 2
            pod:
              containers:
                dispatcher:
                  resources:
                    requests:
                      memory: 256Mi
                      cpu: 250m
                    limits:
                      memory: 2048Mi
                      cpu: 2000m
                  image:
                    repository: ghcr.io/brandonros/dotnet-message-hub/dispatcher
                    tag: cc9dcd8e6e1b512782e93f925d4be3bfe3a80afa
                  env:
                    ASPNETCORE_ENVIRONMENT:
                      value: Development
                    ASPNETCORE_URLS:
                      value: http://*:3000
                    RABBITMQ_URI:
                      value: amqp://rabbitmq.rabbitmq.svc.cluster.local:5672
                    RABBITMQ_USER:
                      value: user
                    RABBITMQ_PASSWORD:
                      value: password
                  ports:
                    http:
                      containerPort: 3000
        service:
          dispatcher:
            type: ClusterIP
            ports:
              http:
                port: 3000
                targetPort: 3000