apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/metrics-server/
  chart: metrics-server
  targetNamespace: kube-system
  version: 0.7.2
  valuesContent: |-
    replicas: 1
