apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: mimir
  namespace: monitoring
spec:
  repo: https://grafana.github.io/helm-charts
  chart: mimir-distributed
  targetNamespace: monitoring
  createNamespace: true
  version: 5.6.0
  valuesContent: |-
    alertmanager:
      resources:
        requests:
          cpu: 20m
    compactor:
      resources:
        requests:
          cpu: 20m
    distributor:
      resources:
        requests:
          cpu: 20m
    ingester:
      replicas: 1
      zoneAwareReplication:
        enabled: false
      resources:
        requests:
          cpu: 20m
    overrides_exporter:
      resources:
        requests:
          cpu: 20m
    querier:
      replicas: 1
      resources:
        requests:
          cpu: 20m
    query_frontend:
      resources:
        requests:
          cpu: 20m
    query_scheduler:
      replicas: 1
      resources:
        requests:
          cpu: 20m
    ruler:
      resources:
        requests:
          cpu: 20m
    store_gateway:
      zoneAwareReplication:
        enabled: false
      resources:
        requests:
          cpu: 20m
    minio:
      resources:
        requests:
          cpu: 20m
    rollout_operator:
      resources:
        requests:
          cpu: 20m
