apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  targetNamespace: traefik
  createNamespace: true
  version: 34.4.0
  valuesContent: |-
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
      
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP
        tls:
          enabled: true
        
    gateway:
      enabled: false

    logs:
      general:
        level: TRACE
      access:
        enabled: true

    providers:
      kubernetesIngress:
        enabled: false

      kubernetesGateway:
        enabled: true
