apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pgbouncer
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/brandonros/hull-wrapper/master/
  chart: hull-wrapper
  targetNamespace: pgbouncer
  createNamespace: true
  version: 0.2.0
  valuesContent: |-
    hull:
      config:
        general:
          nameOverride: pgbouncer
          rbac: false
          noObjectNamePrefixes: true
      objects:
        serviceaccount:
          default:
            enabled: false
        
        service:
          pgbouncer:
            type: ClusterIP
            ports:
              postgres:
                port: 5433
                targetPort: 5433
        
        deployment:
          pgbouncer:
            replicas: 1
            pod:
              containers:
                pgbouncer:
                  image:
                    repository: edoburu/pgbouncer
                    tag: v1.24.1-p1
                  env:
                    AUTH_TYPE:
                      value: scram-sha-256
                    LISTEN_PORT:
                      value: 5433
                    DATABASE_URL:
                      value: 'postgres://postgres:Test_Password123!@postgresql.postgresql.svc.cluster.local:5432/ledgerr'
                    
                    # MASSIVE CONNECTION POOL SCALING
                    MAX_CLIENT_CONN:
                      value: "5000"        # Was 1000, now 5000
                    DEFAULT_POOL_SIZE:
                      value: "500"         # Was 250, now 500 per database
                    MAX_DB_CONNECTIONS:
                      value: "1500"        # Was 500, now 1500 total backend
                    POOL_MODE:
                      value: "transaction" # Keep transaction mode
                    
                    # Performance Tuning
                    RESERVE_POOL_SIZE:
                      value: "50"          # Was 10, now 50
                    RESERVE_POOL_TIMEOUT:
                      value: "3"           # Faster failover
                    
                    # Aggressive Timeout Settings for Load Testing
                    SERVER_IDLE_TIMEOUT:
                      value: "300"         # Was 600, now 5 minutes
                    CLIENT_IDLE_TIMEOUT:
                      value: "0"           # Keep disabled
                    SERVER_CONNECT_TIMEOUT:
                      value: "10"          # Was 15, now 10 seconds
                    QUERY_TIMEOUT:
                      value: "60"          # Was 30, now 60 seconds
                    
                    # Minimal logging for performance
                    LOG_CONNECTIONS:
                      value: "0"
                    LOG_DISCONNECTIONS:
                      value: "0"
                    LOG_POOLER_ERRORS:
                      value: "1"
                    LOG_STATS:
                      value: "1"
                    STATS_PERIOD:
                      value: "30"          # More frequent stats
                    
                    # Network optimization
                    TCP_KEEPALIVE:
                      value: "1"
                    TCP_KEEPCNT:
                      value: "3"
                    TCP_KEEPIDLE:
                      value: "300"         # More aggressive
                    TCP_KEEPINTVL:
                      value: "15"          # More frequent
                    
                    ADMIN_USERS:
                      value: "postgres"
                    STATS_USERS:
                      value: "postgres"
                  
                  ports:
                    pgbouncer:
                      containerPort: 5433
                  
                  # Increased resources for pgbouncer
                  resources:
                    requests:
                      cpu: "1000m"         # Was 500m
                      memory: "1Gi"        # Was 512Mi
                    limits:
                      cpu: "2000m"         # Was 1000m
                      memory: "2Gi"        # Was 1Gi