deployment:
  replicas: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1000m"
    memory: "1024Mi"

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true
    
gateway:
  enabled: false

logs:
  general:
    level: DEBUG
  access:
    enabled: true

providers:
  kubernetesIngress:
    enabled: false

  kubernetesGateway:
    enabled: true
    experimentalChannel: true
