{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ .issuerName }}
    kind: Issuer
  dnsNames:
  {{- range .dnsNames }}
  - {{ . }}
  {{- end }}
{{- end }}
