{{- range .Values.httpRedirectRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  parentRefs:
  - name: {{ .gatewayName }}
    namespace: {{ .gatewayNamespace }}
    kind: Gateway
  hostnames:
  {{- range .hostnames }}
  - {{ . }}
  {{- end }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: {{ .scheme }}
        statusCode: {{ .statusCode }}
{{- end }}
