{{- range .Values.httpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  parentRefs:
  - name: {{ .gatewayName }}
    namespace: {{ .gatewayNamespace }}
    kind: Gateway
    sectionName: {{ .sectionName }}
  hostnames:
  {{- range .hostnames }}
  - {{ . }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .backendService.name }}
      namespace: {{ .backendService.namespace }}
      port: {{ .backendService.port }}
      kind: Service
      weight: {{ .backendService.weight }}
{{- end }}
