{{- range .Values.issuers }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  acme:
    email: {{ .email }}
    server: {{ .server }}
    privateKeySecretRef:
      name: {{ .privateKeySecretName }}
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: {{ .httpGatewayName }}
              namespace: {{ .httpGatewayNamespace }}
              kind: Gateway
{{- end }}
