apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nginx
  namespace: kube-system
spec:
  repo: https://raw.githubusercontent.com/brandonros/hull-wrapper/master/
  chart: hull-wrapper
  targetNamespace: nginx
  createNamespace: true
  version: 0.2.0
  valuesContent: |-
    hull:
      config:
        general:
          nameOverride: nginx
          rbac: false
          noObjectNamePrefixes: true
      objects:
        serviceaccount:
          default:
            enabled: false
        
        configmap:
          static-files:
            data:
              index.html:
                inline: |
                  <!DOCTYPE html>
                  <html>
                  <head>
                      <title>Welcome to Nginx</title>
                      <link rel="stylesheet" href="style.css">
                  </head>
                  <body>
                      <h1>Welcome to Your Static Site</h1>
                      <p>This is served from Kubernetes ConfigMap!</p>
                      <div class="container">
                          <h2>Your Cloud Infrastructure</h2>
                          <ul>
                              <li>K3s Kubernetes Cluster ✓</li>
                              <li>Traefik Ingress ✓</li>
                              <li>Nginx Static Files ✓</li>
                          </ul>
                      </div>
                  </body>
                  </html>
              
              style.css:
                inline: |
                  body {
                      font-family: Arial, sans-serif;
                      margin: 0;
                      padding: 20px;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                  }
                  
                  .container {
                      max-width: 800px;
                      margin: 0 auto;
                      background: rgba(255, 255, 255, 0.1);
                      padding: 20px;
                      border-radius: 10px;
                      backdrop-filter: blur(10px);
                  }
                  
                  h1, h2 {
                      text-align: center;
                  }
                  
                  ul {
                      list-style: none;
                      padding: 0;
                  }
                  
                  li {
                      padding: 10px;
                      margin: 5px 0;
                      background: rgba(255, 255, 255, 0.2);
                      border-radius: 5px;
                  }
              
              config.js:
                inline: |
                  // Add any JavaScript configuration here
                  console.log('Static site loaded successfully!');
        
        service:
          nginx:
            type: ClusterIP
            ports:
              http:
                port: 80
                targetPort: 80
        
        deployment:
          nginx:
            replicas: 2
            pod:
              containers:
                nginx:
                  image:
                    repository: nginx
                    tag: alpine
                  
                  ports:
                    http:
                      containerPort: 80
                  
                  volumeMounts:
                    static-files:
                      name: static-files
                      mountPath: /usr/share/nginx/html
                  
                  resources:
                    requests:
                      cpu: 50m
                      memory: 64Mi
                    limits:
                      cpu: 200m
                      memory: 128Mi
              
              volumes:
                static-files:
                  configMap:
                    name: static-files