apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: kafka-reference-grant
  namespace: kafka
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: TCPRoute
    namespace: traefik
  to:
  - group: ""
    kind: Service
    name: kafka
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: kafka-tcproute
  namespace: traefik
spec:
  parentRefs:
  - name: debian-k3s-gateway
    namespace: traefik
    kind: Gateway
    sectionName: kafka-external
  rules:
    - backendRefs:
      - name: kafka
        namespace: kafka
        port: 9095
        kind: Service
        weight: 100
