apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana.yaml
  - ./prometheus.yaml
  - ./tempo.yaml
  - ./linkerd-viz.yaml
  - ./graphite.yaml
  - ./kibana.yaml
  - ./elasticsearch.yaml
