apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # monitoring
  #- ./grafana.yaml
  #- ./prometheus.yaml
  #- ./tempo.yaml
  #- ./graphite.yaml

  # linkerd-viz
  #- ./linkerd-viz.yaml

  # kafka
  #- ./kafka.yaml

  # redis
  #- ./redis.yaml

  # postgresql
  #- ./postgresql.yaml

  # rabbitmq
  #- ./rabbitmq.yaml

  # minio
  #- ./minio.yaml

  # wordpress
  - ./wordpress.yaml
