apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: rabbitmq-reference-grant
  namespace: rabbitmq
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: TCPRoute
    namespace: traefik
  to:
  - group: ""
    kind: Service
    name: rabbitmq
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: rabbitmq-tcproute
  namespace: traefik
spec:
  parentRefs:
  - name: debian-k3s-gateway
    namespace: traefik
    kind: Gateway
    sectionName: rabbitmq
  rules:
    - backendRefs:
      - name: rabbitmq
        namespace: rabbitmq
        port: 5672
        kind: Service
        weight: 100
