apiVersion: batch/v1
kind: Job
metadata:
  name: duckdns-updater
spec:
  template:
    spec:
      containers:
      - name: duckdns-updater
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Updating DuckDNS record for ${DUCKDNS_DOMAIN}..."
            response=$(curl -sSL "https://www.duckdns.org/update?domains=${DUCKDNS_DOMAIN}&token=${DUCKDNS_TOKEN}")
            if [ "$response" = "OK" ]; then
                echo "Successfully updated DuckDNS record"
                exit 0
            else
                echo "Failed to update DuckDNS record. Response: ${response}"
                exit 1
            fi
        env:
        - name: DUCKDNS_DOMAIN
          value: "wordpresstest5555.duckdns.org"
      restartPolicy: OnFailure