- name: install k3s
  hosts: my_instance
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Check if installed
      ansible.builtin.command:
        cmd: "which kubectl"
      register: kubectl_check
      ignore_errors: yes

    - name: Download and install if not installed
      ansible.builtin.shell: |
        # install k3s
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable=traefik --disable=metrics-server" sh -

        # trust cluster ssl
        cp /var/lib/rancher/k3s/server/tls/server-ca.crt /usr/local/share/ca-certificates/
        update-ca-certificates

        # add coredns in the cluster to node dns resolution chain
        if ! grep -q "nameserver 10.43.0.10" /etc/resolvconf/resolv.conf.d/tail; then
          echo "nameserver 10.43.0.10" >> /etc/resolvconf/resolv.conf.d/tail
          resolvconf -u
        fi
      when: kubectl_check.rc != 0

- name: configure kubeconfig for user
  hosts: my_instance
  gather_facts: false
  become: true
  become_user: debian
  tasks:
    - name: Check if present
      ansible.builtin.stat:
        path: /home/debian/.kube/config
      register: file_check

    - name: get kubeconfig
      when: not file_check.stat.exists
      become: true
      become_user: root
      register: kubeconfig
      ansible.builtin.shell: "k3s kubectl config view --raw"

    - name: configure kubeconfig for user
      when: not file_check.stat.exists    
      ansible.builtin.shell: |
        mkdir /home/debian/.kube 2> /dev/null
        echo "{{ kubeconfig.stdout }}" > /home/debian/.kube/config
        chmod 600 /home/debian/.kube/config

    - name: add to .bashrc
      when: not file_check.stat.exists    
      ansible.builtin.shell: |
        echo 'export KUBECONFIG=/home/debian/.kube/config' >> ~/.bashrc

- name: wait for k3s to be rolled out
  hosts: my_instance
  gather_facts: false
  environment:
    KUBECONFIG: "/home/debian/.kube/config"
  tasks:
    - name: wait for k3s to be rolled out
      ansible.builtin.shell: |
        kubectl wait deployment -n kube-system coredns --for create --timeout=300s
        kubectl wait deployment -n kube-system local-path-provisioner --for create --timeout=300s

        kubectl wait deployment -n kube-system coredns --for condition=Available=True --timeout=300s
        kubectl wait deployment -n kube-system local-path-provisioner --for condition=Available=True --timeout=300s

- name: fetch configuration files
  hosts: my_instance
  gather_facts: false
  tasks:
    - name: fetch kubeconfig
      fetch:
        src: /home/debian/.kube/config
        dest: "{{playbook_dir}}/../server-files/kubeconfig"
        flat: yes

    - name: fetch server CA certificate
      become: true
      become_user: root
      fetch:
        src: /var/lib/rancher/k3s/server/tls/server-ca.crt
        dest: "{{playbook_dir}}/../server-files/server-ca.crt"
        flat: yes

    - name: fetch server CA key
      become: true
      become_user: root
      fetch:
        src: /var/lib/rancher/k3s/server/tls/server-ca.key
        dest: "{{playbook_dir}}/../server-files/server-ca.key"
        flat: yes
