- name: setup user
  hosts: my_instance
  become: true
  become_user: root
  gather_facts: false
  vars:
    hashed_password: "{{ 'foobar123' | password_hash('sha512') }}"
  tasks:
    - name: Ensure user "debian" exists
      ansible.builtin.user:
        name: debian
        shell: /bin/bash
        groups: sudo
        create_home: true
        home: /home/debian
        append: yes
        password: "{{ hashed_password }}"

    - name: add ssh key
      ansible.posix.authorized_key:
        user: debian
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: setup packages
  hosts: my_instance
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: update apt cache
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: yes

    - name: safe upgrade
      ansible.builtin.apt:
        upgrade: safe

    - name: dist upgrade
      ansible.builtin.apt:
        upgrade: dist

    - name: install packages
      ansible.builtin.apt:
        state: present
        pkg:
          - acl
          - htop
          - psmisc

    - name: auto remove
      ansible.builtin.apt:
        autoremove: yes

    - name: Check if k9s is installed
      ansible.builtin.command: which k9s
      register: k9s_check
      ignore_errors: true
      changed_when: false

    - name: install k9s
      when: k9s_check.rc != 0
      ansible.builtin.shell: |
        wget https://github.com/derailed/k9s/releases/download/v0.32.7/k9s_linux_amd64.deb
        apt install -y ./k9s_linux_amd64.deb
        rm k9s_linux_amd64.deb
