- name: deploy wireguard
  hosts: my_instance
  gather_facts: false
  environment:
    KUBECONFIG: "/home/debian/.kube/config"
  vars:
    playbook_dir_parent: "{{ playbook_dir | dirname }}"
  tasks:
    - name: Read local wireguard yaml
      ansible.builtin.slurp:
        src: "{{ playbook_dir_parent }}/helm/wireguard.yaml"
      delegate_to: localhost
      become: false
      register: wireguard_yaml
      
    - name: rollout
      become: true
      become_user: debian
      timeout: 300      
      ansible.builtin.shell: |
        cat << 'EOF' | kubectl apply -f -
        {{ wireguard_yaml.content | b64decode }}
        EOF
        kubectl wait daemonset -n wireguard wireguard-wireguard --for create --timeout=300s
        kubectl wait daemonset -n wireguard wireguard-wireguard --for condition=Available=True --timeout=300s
