apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: pdf-generator
  namespace: pdf-generator
spec:
  repo: https://raw.githubusercontent.com/brandonros/hull-wrapper/master/
  chart: hull-wrapper
  targetNamespace: pdf-generator
  version: 0.2.0
  valuesContent: |-
    hull:
      config:
        general:
          nameOverride: pdf-generator
          rbac: false
          noObjectNamePrefixes: true
      objects:
        serviceaccount:
          default:
            enabled: false
        deployment:
          pdf-generator:
            replicas: 4
            annotations:
              linkerd.io/inject: enabled
              config.linkerd.io/proxy-log-level: debug
            pod:
              containers:
                main:
                  resources:
                    requests:
                      memory: 256Mi
                      cpu: 250m
                    limits:
                      memory: 2048Mi
                      cpu: 2000m
                  image:
                    repository: ghcr.io/brandonros/pdf-generator
                    tag: 329e2b7f410ab5212afa5975b68b64ff785349b9
                  env:
                    CHROMIUM_PATH:
                      value: /usr/bin/chromium
                    MAX_CONCURRENCY:
                      value: 15
                  ports:
                    http:
                      containerPort: 3000
        service:
          pdf-generator:
            type: ClusterIP
            ports:
              http:
                port: 3000
                targetPort: 3000
