apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: elasticsearch
  targetNamespace: elasticsearch
  valuesContent: |-
    global:
      kibanaEnabled: true
    security:
      enabled: true
    master:
      masterOnly: false
      replicaCount: 1
      resources:
        limits:
            memory: 1Gi
    data:
      replicaCount: 0
    coordinating:
      replicaCount: 0
    ingest:
      replicaCount: 0
    kibana:
      security:
        auth:
          enabled: true
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 512Mi
