apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wireguard
  namespace: kube-system
spec:
  repo: https://bryopsida.github.io/wireguard-chart/
  chart: wireguard
  createNamespace: true
  targetNamespace: wireguard
  valuesContent: |-
    daemonSet: true
    runPodOnHostNetwork: true
    useHostPort: true
    hostPort: 51820
    replicaCount: 1
    autoscaling:
      enabled: false
    service:
      enabled: false
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
      privileged: true
    wireguard:
      serverAddress: 10.34.0.1/24
      serverCidr: 10.34.0.0/24
      natAddSourceNet: true
      interfaceOpts:
        PostUp: "iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE"
        PostDown: "iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE"
      clients: 
        - FriendlyName: client1
          AllowedIPs: 10.34.0.2/32
          PublicKey: RWWN+Dz5dIXv3ePmE2EnQF8AG9ea2+j0jsFp8rLri34=
          PersistentKeepalive: 25