apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: wireguard
  namespace: kube-system
spec:
  repo: https://bryopsida.github.io/wireguard-chart/
  chart: wireguard
  targetNamespace: wireguard
  valuesContent: |-
    wireguard:
      serverAddress: 10.34.0.1/24
      serverCidr: 10.34.0.0/24
      natAddSourceNet: true
      interfaceOpts: {}
      clients: []
