apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: wordpress-httproute
  namespace: traefik
spec:
  parentRefs:
  - name: gateway
    namespace: traefik
    kind: Gateway
    sectionName: websecure
  hostnames:
  - wordpresstest5555.duckdns.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: wordpress
      namespace: wordpress
      port: 80
      kind: Service
      weight: 100
