apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  targetNamespace: cert-manager
  version: v1.15.3 # https://github.com/cert-manager/cert-manager/issues/7337
  valuesContent: |-
    crds:
      enabled: true
