apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pdf-generator-httproute
  namespace: traefik
spec:
  parentRefs:
  - name: gateway
    namespace: traefik
    kind: Gateway
    sectionName: websecure
  hostnames:
  - pdf-generator5555.duckdns.org
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pdf-generator
      namespace: pdf-generator
      port: 3000
      kind: Service
      weight: 100
